app_frontend:
    resource: '@AppBundle/Controller/Frontend'
    type: annotation

#app_backend:
 #   resource: '@AppBundle/Controller/Backend'
  #  type: annotation

# Admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin